### ISSUE TITLE
Failed to activate the QuickJumpPlus package

### ISSUE THREAD

**Issue by lmartins** [ca77y/atom-quickjump#1]
Fails whenever I try to run the quick jump command.

**Atom Version**: 0.208.0
**System**: Mac OS X 10.10.4
**Thrown From**: [QuickJumpPlus](https://github.com/ca77y/atom-quickjump) package, v0.1.4
### Stack Trace

Failed to activate the QuickJumpPlus package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/luismartins/.atom/packages/QuickJumpPlus/lib/quickjump-view.coffee:1:1)
  at /Users/luismartins/.atom/packages/QuickJumpPlus/lib/quickjump-view.coffee:6:3
  at Object.<anonymous> (/Users/luismartins/.atom/packages/QuickJumpPlus/lib/quickjump-view.coffee:204:5)
  at Object.<anonymous> (/Users/luismartins/.atom/packages/QuickJumpPlus/lib/quickjump-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/luismartins/.atom/packages/QuickJumpPlus/lib/quickjump.coffee:2:17)
  at Object.<anonymous> (/Users/luismartins/.atom/packages/QuickJumpPlus/lib/quickjump.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:707:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:255:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:234:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:770:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -0:11.8.0 pane:show-previous-item (atom-text-editor.editor.mini.is-focused)
 11x -0:10.4.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:08.5.0 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:04.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:04.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:02.2.0 quickjump:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ],
    "disabledPackages": [
      "symbols-view",
      "linter-jscs",
      "autocomplete",
      "autohide-tree-view",
      "powerline",
      "language-objective-c",
      "archive-view",
      "language-clojure",
      "language-c",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "welcome",
      "git-difftool",
      "layout-manager",
      "git-control",
      "gulp-control",
      "select-to-character"
    ],
    "projectHome": "/Users/luismartins/Sites",
    "ignoredNames": [
      ".DS_Store",
      "bower_components",
      "node_modules",
      "build",
      "jspm_packages"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
QuickJumpPlus, v0.1.4
atom-alignment, v0.12.1
atom-ctags, v4.1.2
chester-atom-syntax, v0.1.1
color-picker, v2.0.4
css-snippets, v0.8.0
docblockr, v0.7.2
emmet, v2.3.10
javascript-snippets, v1.0.0
language-less, v0.27.0
linter, v0.12.7
linter-jshint, v0.1.6
linter-php, v0.0.15
minimap, v4.9.4
minimap-bookmarks, v0.1.0
php-debug, v0.1.2
php-twig, v4.0.0
selection-outlines, v0.2.0
symbols-tree-view, v0.9.3
vim-mode, v0.51.0
vim-surround, v0.6.1
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by victorteokw** [comment]
Same issue with Atom version 1.0.15

**Comment by ihorskyi** [comment]
same here with Atom v 1.0.19
